name: Github-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  chromeHeadLess:
    name: Chrome Headless
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test